<template>
    <div class="index">
        <b-navbar toggleable="lg" type="dark" variant="primary" sticky>
            <b-navbar-brand href="#" class="logo">
                SmartIntentNN
                <b-badge class="version" variant="danger">Alpha v0.1</b-badge>
            </b-navbar-brand>
            <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
            <b-collapse id="nav-collapse" is-nav>
                <b-navbar-nav>
                    <b-nav-item active>Home</b-nav-item>
                    <b-nav-item href="highlight">Highlight</b-nav-item>
                    <b-nav-item href="evaluate">Evaluation</b-nav-item>
                </b-navbar-nav>

                <!-- Right aligned nav items -->
                <b-navbar-nav class="ml-auto">
                    <b-nav-form @submit.prevent="loadData">
                        <b-form-input
                            v-model="keyword"
                            class="search"
                            placeholder="Id/Address"
                            size="sm"
                        />
                        <b-button type="button" size="sm" @click="loadData">Search</b-button>
                    </b-nav-form>

                    <b-nav-item-dropdown text="Lang" right>
                        <b-dropdown-item href="#">EN</b-dropdown-item>
                    </b-nav-item-dropdown>
                </b-navbar-nav>
            </b-collapse>
        </b-navbar>
        <div v-if="sourceCode" class="fullscreen">
            <div class="info text-center">
                <b-spinner
                    v-show="loading"
                    variant="primary"
                    type="grow"
                    label="Spinning"
                ></b-spinner>
                <p v-show="id && !loading">
                    Smart Contract ID: <b>{{ id }}</b>
                </p>
                <p v-show="address && !loading">
                    Smart Contract Address: <b>{{ address }}</b>
                </p>
            </div>
            <div v-if="sourceCode" class="source-code">
                <PredictModal
                    v-show="showModal"
                    :id="id"
                    :address="address"
                    :status="showModal"
                    @close="showModal = false"
                />
                <div class="text-center">
                    <b-button-group>
                        <b-button variant="success" @click="tab = 0">Context 📜</b-button>
                        <b-button variant="primary" @click="tab = 1">CCTree 🌲</b-button>
                        <b-button variant="warning" @click="tab = 2">OpCode 🔧</b-button>
                        <b-button variant="danger" @click="showModal = true">Predict 👍</b-button>
                    </b-button-group>
                </div>
                <div v-if="tab === 0" class="tab-code">
                    <div v-for="(item, index) in sourceCode" :key="index" class="source-code">
                        <h3>{{ index }}</h3>
                        <vue-code-highlight language="solidity">
                            <pre> {{ item }} </pre>
                        </vue-code-highlight>
                    </div>
                </div>
                <div v-if="tab === 1" class="tab-tree">
                    <h3>Code Tree</h3>
                    <v-chart class="chart" :option="option1" />
                    <h3>ABI Tree</h3>
                    <v-chart class="chart" :option="option2" />
                    <h3>MethodIdentifiers Tree</h3>
                    <v-chart class="chart" :option="option3" />
                </div>
                <div v-if="tab === 2" class="tab-opcode">
                    <div v-for="(item, index) in opCode" :key="index" class="source-code">
                        <h3>{{ index }}</h3>
                        <p>{{ item }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div v-if="!sourceCode && !loading" class="replace">
            404 NOT FOUND
            <br />
            TRY ANOTHER PK OR ADDRESS
        </div>
        <footer class="text-center footer">
            Powered by
            <a href="https://www.tensorflow.org/js" target="_blank">Tensorflow.js</a>
            Generated by
            <a href="https://gitlab.com/web3se/smartvue" target="_blank">Gitlab CI/CD</a>
        </footer>
        <div v-show="false">
            <vue-code-highlight
                v-for="(item, index) in tree"
                :key="index"
                :ref="item.key"
                language="solidity"
            >
                <pre style="margin: 0;">{{ item.code }}</pre>
            </vue-code-highlight>
        </div>
    </div>
</template>

<script>
import { component as VueCodeHighlight } from 'vue-code-highlight'
import 'prismjs/themes/prism-okaidia.css'
import 'prismjs/components/prism-solidity'
import $ from '~/utils/tool'
import option from '~/utils/option'
/*
const COLOR1 = '#007bff'
const COLOR2 = '#ffc107'
const COLOR3 = '#28a745'
const COLOR4 = '#17a2b8'
const COLOR5 = '#dc3545'
*/

export default {
    name: 'IndexPage',
    components: {
        VueCodeHighlight
    },
    data() {
        return {
            tab: 0,
            loading: false,
            keyword: '1',
            id: '',
            address: '',
            showModal: false,
            sourceCode: null,
            opCode: null,
            tree: [],
            option1: $.getObject(option),
            option2: $.getObject(option),
            option3: $.getObject(option)
        }
    },
    mounted() {
        this.loadData()
    },
    methods: {
        async loadData() {
            try {
                this.loading = true
                const res = await $.get('code/get', { key: this.keyword })
                if (res) {
                    this.id = res.Id
                    this.address = res.ContractAddress
                    this.sourceCode = this.getContractMap(res.SourceCode)
                    this.opCode = JSON.parse(res.OpCode)
                    // handle trees
                    this.option1.series[0].tooltip.padding = 0
                    this.option1.series[0].tooltip.borderWidth = 0
                    const tree = JSON.parse(res.SourceCodeMap)
                    this.option1.series[0].data = this.getTree(tree, 1)
                    this.option2.series[0].data = this.getTree(JSON.parse(res.ABI), 2)
                    this.option3.series[0].data = this.getTree(JSON.parse(res.MethodIdentifiers), 3)
                    this.tree = []
                    for (const i in tree)
                        for (const j in tree[i]) this.tree.push({ key: i + j, code: tree[i][j] })
                } else {
                    this.sourceCode = null
                    this.opCode = []
                    this.abi = []
                }
            } catch (e) {
                this.id = ''
                this.sourceCode = null
                this.address = ''
                this.opCode = null
            } finally {
                this.loading = false
            }
        },
        getContractMap(sourceCode) {
            const contracts = $.getContracts(sourceCode)
            const data = {}
            for (const item of contracts) {
                const word = $.getContractName(item)
                data[word] = item
            }
            return data
        },
        // MethodIdentifiers
        // type 1 code
        // type 2 abi
        // type 3 MethodIdentifiers
        getTree(tree, type = 1) {
            const data = { name: 'Smart Contract', children: [], itemStyle: { color: '#000' } }
            for (const i in tree) {
                const data2 = { name: i, children: [], collapsed: Object.keys(tree[i]).length > 15 }
                for (const j in tree[i])
                    data2.children.push({
                        name: type === 2 ? `${tree[i][j].type} ${tree[i][j].name || ''}` : j,
                        tooltip: {
                            position(point, params, dom, rect, size) {
                                if (type === 1) {
                                    const obj = { top: point[1] + 10 }
                                    obj[['left', 'right'][+(point[0] < size.viewSize[0] / 2)]] = 5
                                    return obj
                                }
                            },
                            formatter: () => {
                                if (type === 1) {
                                    const el = this.$refs[i + j][0]
                                    return el.$el.innerHTML
                                } else if (type === 2) {
                                    let str = ''
                                    for (const item of tree[i][j].inputs)
                                        str += `${item.type} ${item.name}, `
                                    return str
                                } else {
                                    return tree[i][j]
                                }
                            }
                        }
                    })
                data.children.push(data2)
            }
            return [data]
        }
    }
}
</script>
<style scoped>
.fullscreen {
    margin-top: 20px;
    min-height: 90vh;
}
h3 {
    font-size: 25px;
    line-height: 40px;
}
.info p {
    font-size: 0.9rem;
}
.code {
    width: 100%;
    margin: 0 auto;
}
.tab-tree {
    width: 900px;
    margin: 0 auto;
}
.chart {
    width: 900px;
    height: 900px;
    margin: 0 auto;
    margin-bottom: 20px;
    border: solid 1px #ccc;
}
.search {
    width: 360px;
}
.code.opcode {
    white-space: inherit;
}
.source-code {
    width: 95%;
    margin: 0 auto;
    margin-top: 1rem;
    font-size: 0.8rem;
    max-width: 1200px;
}
.title {
    font-size: 1rem;
    line-height: 1.2rem;
}
.form {
    padding: 50px 20px 20px 20px;
    display: flex;
    justify-items: center;
    align-content: center;
}
.footer {
    padding: 20px 0;
}
.logo {
    position: relative;
}
.version {
    transform: scale(0.65);
    position: absolute;
    right: -50px;
    top: -5px;
}
.btn {
    font-size: 1rem;
}
.replace {
    padding: 33vh 0;
    text-align: center;
    font-size: 3rem;
    color: #ccc;
}
</style>
<style>
.index .language-solidity {
    margin: 0 !important;
}
</style>
