<template>
    <div class="index">
        <b-navbar toggleable="lg" type="dark" variant="primary" sticky>
            <b-navbar-brand href="#" class="logo">
                SmartIntentNN
                <b-badge class="version" variant="danger">Alpha v0.1</b-badge>
            </b-navbar-brand>
            <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
            <b-collapse id="nav-collapse" is-nav>
                <b-navbar-nav>
                    <b-nav-item active>Home</b-nav-item>
                    <b-nav-item href="highlight">Highlight</b-nav-item>
                    <b-nav-item href="evaluate">Evaluation</b-nav-item>
                </b-navbar-nav>

                <!-- Right aligned nav items -->
                <b-navbar-nav class="ml-auto">
                    <b-nav-form @submit.prevent="loadData">
                        <b-form-input v-model="keyword" class="search" placeholder="Id/Address" size="sm" />
                        <b-button type="button" size="sm" @click="loadData">Search</b-button>
                    </b-nav-form>

                    <b-nav-item-dropdown text="Lang" right>
                        <b-dropdown-item href="#">EN</b-dropdown-item>
                    </b-nav-item-dropdown>
                </b-navbar-nav>
            </b-collapse>
        </b-navbar>

        <!--upload modal-->
        <transition name="fade">
            <UploadModal v-if="showModal2" @embed="predict" @close="showModal2 = false" />
        </transition>
        <!--predict modal-->
        <transition name="fade">
            <PredictModal v-if="showModal" :id="id" :address="address" :content="content" @close="showModal = false" />
        </transition>

        <div class="fullscreen">
            <div class="info text-center">
                <b-spinner v-show="loading" variant="primary" type="grow" label="Spinning"></b-spinner>
                <p v-show="id && !loading">
                    Database ID: <b>{{ id }}</b>
                </p>
                <p v-show="address && !loading">
                    Name: <b>{{ name }}</b>
                </p>
                <p v-show="address && !loading">
                    Address: <b>{{ address }}</b>
                </p>
            </div>

            <div class="content">
                <div class="text-center">
                    <b-button-group>
                        <b-button variant="success" @click="tab = 0">Context 📜</b-button>
                        <b-button variant="primary" @click="tab = 1">CCTree 🌲</b-button>
                        <!--
                        <b-button variant="warning" @click="tab = 2">OpCode ⚙️</b-button>
                        -->
                        <b-button variant="danger" @click="showModal = true">Predict 👍</b-button>
                    </b-button-group>
                    <b-button variant="info" class="upload" block @click="showModal2 = true">
                        Upload my smart contract
                        <b-badge variant="danger">New!</b-badge>
                    </b-button>
                </div>

                <div v-if="tab === 0" class="tab-code">
                    <vue-code-highlight v-if="sourceCode" language="solidity">
                        <pre> {{ sourceCode }} </pre>
                    </vue-code-highlight>
                </div>

                <div v-if="tab === 1" class="tab-tree">
                    <h3>Code Tree</h3>
                    <v-chart class="chart" :option="option1" />
                    <!--
                    <h3>ABI Tree</h3>
                    <v-chart class="chart" :option="option2" />
                    <h3>MethodIdentifiers Tree</h3>
                    <v-chart class="chart" :option="option3" />
                    -->
                </div>
                <div v-if="tab === 2 && opCode" class="tab-opcode">
                    <div v-for="(item, index) in opCode" :key="index" class="source-code">
                        <h3>{{ index }}</h3>
                        <div class="language-solidity">{{ item }}</div>
                    </div>
                </div>
            </div>
        </div>
        <div v-if="!sourceCode && !loading" class="replace">
            404 NOT FOUND
            <br />
            TRY ANOTHER PK OR ADDRESS
        </div>
        <footer class="text-center footer">
            Powered by
            <a href="https://www.tensorflow.org/js" target="_blank">Tensorflow.js</a>
            Generated by
            <a href="https://gitlab.com/web3se/smartvue" target="_blank">Gitlab CI/CD</a>
        </footer>
        <div v-show="false">
            <vue-code-highlight v-for="(item, index) in tree" :key="index" :ref="item.key" language="solidity">
                <pre style="margin: 0;">{{ item.code }}</pre>
            </vue-code-highlight>
        </div>
    </div>
</template>

<script>
import $ from '~/utils/tool'
import option from '~/utils/option'

export default {
    name: 'IndexPage',
    data() {
        return {
            tab: 0,
            loading: false,
            keyword: '1',
            id: 0,
            name: '',
            content: null,
            address: '',
            showModal: false,
            showModal2: false,
            sourceCode: '',
            opCode: null,
            tree: [],
            option1: $.getObject(option),
            option2: $.getObject(option),
            option3: $.getObject(option)
        }
    },
    watch: {
        showModal2(v) {
            if (!v) this.content = null
        }
    },
    mounted() {
        this.loadData()
    },
    methods: {
        async loadData() {
            try {
                this.loading = true
                this.id = ''
                this.address = ''
                this.sourceCode = ''
                this.option1.series[0].data = []
                this.tree = []
                const res = await $.get('code/get', { key: this.keyword })
                if (res) {
                    this.id = res.Id
                    this.address = res.ContractAddress
                    this.name = res.ContractName
                    this.sourceCode = res.SourceCode

                    // generate tree
                    // this.opCode = JSON.parse(res.OpCode)
                    // handle trees
                    this.option1.series[0].tooltip.padding = 0
                    this.option1.series[0].tooltip.borderWidth = 0
                    const tree = res.SourceCodeMap
                    // generate code snippets template for charts
                    for (const i in tree)
                        for (const j in tree[i]) this.tree.push({ key: i + j, code: tree[i][j] })
                    this.option1.series[0].data = this.getTree(tree, 1)
                    // this.option2.series[0].data = this.getTree(JSON.parse(res.ABI), 2)
                    // this.option3.series[0].data = this.getTree(JSON.parse(res.MethodIdentifiers), 3)
                }
            } catch (e) {
                console.error(e)
                this.$bvToast.toast(e.message, {
                    title: 'Error Query',
                    variant: 'danger',
                    solid: true
                })
            } finally {
                this.loading = false
            }
        },
        getContractMap(sourceCode) {
            const contracts = $.getContracts(sourceCode)
            const data = {}
            for (const item of contracts) {
                const word = $.getContractName(item)
                data[word] = item
            }
            return data
        },
        // MethodIdentifiers
        // type 1 code
        // type 2 abi
        // type 3 MethodIdentifiers
        getTree(tree, type = 1) {
            const data = { name: this.name, children: [], itemStyle: { color: '#000' } }
            for (const i in tree) {
                const data2 = { name: i, children: [], collapsed: Object.keys(tree[i]).length > 15 }
                for (const j in tree[i])
                    data2.children.push({
                        name: type === 2 ? `${tree[i][j].type} ${tree[i][j].name || ''}` : j,
                        tooltip: {
                            position(point, params, dom, rect, size) {
                                if (type === 1) {
                                    const obj = { top: point[1] + 10 }
                                    obj[['left', 'right'][+(point[0] < size.viewSize[0] / 2)]] = 5
                                    return obj
                                }
                            },
                            formatter: () => {
                                if (type === 1) {
                                    const el = this.$refs[i + j][0]
                                    return el.$el.innerHTML
                                } else if (type === 2) {
                                    let str = ''
                                    for (const item of tree[i][j].inputs)
                                        str += `${item.type} ${item.name}, `
                                    return str
                                } else {
                                    return tree[i][j]
                                }
                            }
                        }
                    })
                data.children.push(data2)
            }
            return [data]
        },
        predict(content) {
            this.content = content
            this.showModal = true
        }
    }
}
</script>
<style scoped>
.fullscreen {
    min-height: 85vh;
}

h3 {
    font-size: 1.5rem;
    margin: 1rem 0;
}

.info,
.content {
    margin-top: 1rem;
}

.info p {
    margin: 0;
    padding: 0.1rem 0;
    font-size: 0.95rem;
}

.code {
    width: 100%;
    margin: 0 auto;
}

.tab-tree {
    margin: 0 auto;
    width: 95%;
    max-width: 800px;
    margin-top: 1rem;
}

.chart {
    width: 100%;
    max-width: 900px;
    height: 95vw;
    max-height: 800px;
    margin: 0 auto;
    border: solid 1px #ccc;
}

.search {
    width: 360px;
}

.code.opcode {
    white-space: inherit;
}

.tab-code {
    width: 95%;
    margin: 0 auto;
    margin-top: 1rem;
    font-size: 0.8rem;
    max-width: 1200px;
}

.title {
    font-size: 1rem;
    line-height: 1.2rem;
}

.form {
    padding: 50px 20px 20px 20px;
    display: flex;
    justify-items: center;
    align-content: center;
}

.footer {
    padding: 20px 0;
}

.logo {
    position: relative;
}

.version {
    transform: scale(0.65);
    position: absolute;
    right: -50px;
    top: -5px;
}

.btn {
    font-size: 1rem;
}

.upload {
    width: 25rem;
    margin: 0 auto;
    margin-top: 1rem;
}

.replace {
    padding: 33vh 0;
    text-align: center;
    font-size: 3rem;
    color: #ccc;
}
</style>
<style>
.index .language-solidity {
    margin: 0 !important;
}
</style>
